################################################################
# Middlewares configuration
################################################################
[http]
  [http.middlewares]
    [http.middlewares.dashboard-auth]
      [http.middlewares.dashboard-auth.basicAuth]
		# Dashboard authentification => user:changeme
        users = [
          "user:$2y$05$vPsxy5O6xJzcdUb4OJdsau38ubCZUMeBpBdeR3mgChUUEY6xmNF8m",
        ]

    [http.middlewares.redirect-to-https]
      [http.middlewares.redirect-to-https.redirectScheme]
        scheme = "https"
        permanent = true

    [http.middlewares.headers-security]
       [http.middlewares.headers-security.headers]
          accessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
          accessControlAllowOriginList = ["https://domain.tld", "https://*.domain.tld"]
          accessControlMaxAge = 100
          addVaryHeader = true
          browserXssFilter = true
          contentTypeNosniff = true
          forceSTSHeader = true
          frameDeny = true
          sslRedirect = true
          stsIncludeSubdomains = true
          stsPreload = true
          customFrameOptionsValue = "SAMEORIGIN"
          referrerPolicy = "same-origin"
          featurePolicy = "vibrate 'self'"
          stsSeconds = 315360000

################################################################
# TLS configuration
################################################################
[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
      ]
      curvePreferences = ["CurveP521","CurveP384"]